import { baseConfig } from '@prc/charting-utilities';
import { BaseConfig as BaseConfigType } from '@prc/charting-utilities';

const independentTickFont = baseConfig.independentAxis.tickLabels.fontFamily;
const independentAxisLabelFont = baseConfig.independentAxis.axisLabel.fontFamily;
const dependentTickFont = baseConfig.dependentAxis.tickLabels.fontFamily;
const dependentAxisLabelFont = baseConfig.dependentAxis.axisLabel.fontFamily;
const tooltipFont = baseConfig.tooltip.style.fontFamily;
const chartLabelFont = baseConfig.labels.fontFamily;

export const dotPlotConfig: BaseConfigType = {
	...baseConfig,
	layout: {
		...baseConfig.layout,
		name: 'chart-builder-chart-4db7cf2e-20a7-4bb5-8b82-dc366bd0b014-chart',
		parentClass: 'wp-chart-builder-wrapper',
		type: 'dot-plot',
		orientation: 'horizontal',
		width: 420,
		height: 200,
		padding: {
			top: 36,
			bottom: 36,
			left: 100,
			right: 20,
		},
		overflowX: 'responsive',
		horizontalRules: true,
	},
	metadata: {
		active: true,
		title: 'Dot Plot Chart',
		subtitle: 'A subtitle for the chart',
		note: 'Note: Add note about the chart',
		source: 'Source: Add source note here',
		tag: 'PEW RESEARCH CENTER',
		alt: '',
	},
	colors: ['#0073A5', '#0090C0', '#C9DEEE', '#9DC7E1', '#71B2D6', '#00557E'],
	plotBands: {
		active: false,
		allowDrag: false,
		allowResize: false,
		dimension: 'x',
		bands: [],
	},
	independentAxis: {
		...baseConfig.independentAxis,
		active: true,
		scale: 'linear',
		dateFormat: '%Y',
		domainPadding: 20,
		showZero: true,
		padding: 60,
		tickAngle: 0,
		tickCount: 5,
		tickFormat: null,
		ticksToLocaleString: false,
		abbreviateTicks: false,
		abbreviateTicksDecimals: 0,
		tickUnit: '',
		tickUnitPosition: 'end',
		customTickFormat: null,
		tickLabels: {
			fontSize: 12,
			padding: 0,
			angle: 0,
			dx: 0,
			dy: 0,
			textAnchor: 'end',
			verticalAnchor: 'middle',
			fill: '#231F20',
			fontFamily: independentTickFont,
			maxWidth: 50,
		},
		axisLabel: {
			fontSize: 12,
			fill: '#231F20',
			padding: 30,
			angle: 0,
			dx: 0,
			dy: 0,
			textAnchor: 'middle',
			verticalAnchor: 'middle',
			fontFamily: independentAxisLabelFont,
			maxWidth: 100,
		},
		axis: {
			stroke: '#756f6b00',
			strokeWidth: 1,
		},
		ticks: {
			stroke: '#756f6b00',
			size: 0,
			strokeWidth: 1,
		},
		grid: {
			stroke: '#d1d1d1',
			strokeOpacity: 0.2,
			strokeWidth: 1,
			strokeDasharray: '',
		},
	},
	dependentAxis: {
		...baseConfig.dependentAxis,
		active: true,
		scale: 'linear',
		padding: 100,
		domain: [0, 100],
		domainPadding: 20,
		showZero: true,
		tickCount: 5,
		tickValues: [0, 50, 100],
		tickFormat: null,
		ticksToLocaleString: false,
		abbreviateTicks: true,
		abbreviateTicksDecimals: 0,
		tickUnit: '',
		tickUnitPosition: 'end',
		customTickFormat: null,
		tickLabels: {
			fontSize: 12,
			fill: '#231F20',
			padding: 15,
			angle: 0,
			dx: 0,
			dy: 0,
			textAnchor: 'end',
			verticalAnchor: 'middle',
			fontFamily: dependentTickFont,
			maxWidth: 50,
		},
		axisLabel: {
			fontSize: 12,
			fill: '#231F20',
			padding: 30,
			angle: 270,
			dx: 0,
			dy: 0,
			textAnchor: 'middle',
			verticalAnchor: 'middle',
			fontFamily: dependentAxisLabelFont,
			maxWidth: 100,
		},
		ticks: {
			stroke: '#756f6b',
			size: 5,
			strokeWidth: 1,
		},
		axis: {
			stroke: '#756f6b',
			strokeWidth: 1,
		},
		grid: {
			stroke: '#00000000',
			strokeOpacity: 0.2,
			strokeWidth: 1,
			strokeDasharray: '',
		},
	},
	dataRender: {
		...baseConfig.dataRender,
		x: 'x',
		y: 'y',
		x2: null,
		y2: null,
		sortKey: 'x',
		sortOrder: 'none',
		categories: ['n1', 'n2'],
		xScale: 'linear',
		yScale: 'linear',
		xFormat: 'YYYY',
		yFormat: '',
		numberFormat: 'en-US',
		isHighlightedColor: '#ECDBAC',
		mapScale: 'threshold',
		mapScaleDomain: [10, 20, 30, 40, 50],
	},
	tooltip: {
		...baseConfig.tooltip,
		active: false,
		headerActive: true,
		headerValue: 'categoryValue',
		format: '{{row}}: {{value}}',
		offsetX: 10,
		offsetY: 10,
		abbreviateValue: false,
		absoluteValue: false,
		toFixedDecimal: 0,
		toLocaleString: true,
		customFormat: null,
		rlsFormat: false,
		dateFormat: '%Y',
		caretPosition: 'bottom',
		deemphasizeSiblings: false,
		deemphasizeOpacity: 0.5,
		style: {
			minWidth: 50,
			maxWidth: 200,
			maxHeight: 100,
			minHeight: 20,
			width: 'auto',
			height: 'auto',
			fontSize: '13px',
			fontFamily: tooltipFont,
			background: 'white',
			border: '1px solid #CBCBCB',
			padding: '10px',
			borderRadius: '0px',
			color: 'black',
		},
	},
	legend: {
		...baseConfig.legend,
		active: true,
		orientation: 'row',
		title: '',
		alignment: 'center',
		offsetX: 0,
		offsetY: 0,
		markerStyle: 'circle',
		borderStroke: '#24202100',
		fill: 'white',
		categories: [],
		labelDelimiter: ' - ',
		labelLower: 'Less than ',
		labelUpper: 'More than ',
	},
	dotPlot: {
		...baseConfig.dotPlot,
		connectPoints: false,
		connectingLine: {
			stroke: '#E6E7E8',
			strokeWidth: 6,
			strokeDasharray: '',
			strokeOpacity: 1,
		},
	},
	errorBars: {
		enabled: true,
		defaultStyles: {
			stroke: '#e6e7e8',
			strokeWidth: 6,
			strokeDasharray: '',
			strokeOpacity: 1,
		},
	},
	nodes: {
		...baseConfig.nodes,
		pointSize: 4,
		pointFill: 'white',
		pointStrokeWidth: 3,
		pointStroke: 'inherit',
		pointCustomSize: null,
	},
	labels: {
		...baseConfig.labels,
		active: true,
		showFirstLastPointsOnly: false,
		color: 'inherit',
		fontWeight: 200,
		fontSize: 10,
		fontFamily: chartLabelFont,
		labelPositionBar: 'inside',
		labelCutoff: 10,
		labelPositionDX: 16,
		labelPositionDY: 0,
		pieLabelRadius: 60,
		abbreviateValue: false,
		absoluteValue: false,
		toLocaleString: true,
		truncateDecimal: true,
		toFixedDecimal: 3,
		labelUnit: '%',
		labelUnitPosition: 'end',
		textAnchor: 'middle',
		customLabelFormat: null,
	},
};

export default dotPlotConfig;

// Sample data for the dot plot with error bars
export const dotPlotData = [
	{
		x: 'Germany',
		n1: '30',
		n2: '40',
		__errorBars: {
			n1: {
				min: '25',
				max: '33',
				stroke: '#4BA5CD',
				strokeWidth: 6,
				strokeLinecap: 'round',
				strokeLinejoin: 'round',
			},
			n2: {
				min: '38',
				max: '42',
				stroke: '#0090C0',
				strokeWidth: 4,
				strokeLinecap: 'round',
				strokeLinejoin: 'round',
			},
		},
	},
	{
		x: 'Spain',
		n1: '50',
		n2: '60',
		__errorBars: {
			n1: {
				min: '44',
				max: '54',
				stroke: '#4BA5CD',
				strokeWidth: 6,
				strokeLinecap: 'round',
				strokeLinejoin: 'round',
			},
			n2: {
				min: '54',
				max: '64',
				stroke: '#0090C0',
				strokeWidth: 4,
				strokeLinecap: 'round',
				strokeLinejoin: 'round',
			},
		},
	},
	{
		x: 'France',
		n1: '60',
		n2: '70',
		__errorBars: {
			n1: {
				min: '57',
				max: '62',
				stroke: '#4BA5CD',
				strokeWidth: 6,
				strokeLinecap: 'round',
				strokeLinejoin: 'round',
			},
			n2: {
				min: '67',
				max: '72',
				stroke: '#0090C0',
				strokeWidth: 4,
				strokeLinecap: 'round',
				strokeLinejoin: 'round',
			},
		},
	},
];
