import { baseConfig, BaseConfig as BaseConfigType } from '@prc/charting-utilities';

const dotPlotConfig: BaseConfigType = {
	...baseConfig,
	layout: {
		...baseConfig.layout,
		type: 'dot-plot',
		width: 640,
		height: 500,
		padding: { top: 20, bottom: 50, left: 100, right: 50 },
		orientation: 'vertical',
	},
	colors: ['#733D47', '#BC7B86', '#9DC7E1', '#bc7b2b', '#eeece4'],
	dataRender: {
		...baseConfig.dataRender,
		xScale: 'linear',
		xFormat: 'MM/YYYY',
		categories: ['y', 'y1', 'y2'],
		sortKey: 'y',
		sortOrder: 'ascending',
	},
	animate: {
		active: false,
		duration: 500,
	},
	dotPlot: {
		...baseConfig.dotPlot,
	},
	line: {
		...baseConfig.line,
		interpolation: 'curveCatmullRom',
		showPoints: true,
		showArea: false,
		strokeWidth: 1,
		strokeDasharray: '5,2',
	},
	nodes: {
		...baseConfig.nodes,
		pointSize: 5,
		pointFill: 'inherit',
		pointStrokeWidth: 1,
	},
	dependentAxis: {
		...baseConfig.dependentAxis,
		label: 'Spending in dollars',
		active: true,
		padding: 50,
		domain: [0, 10],
		domainPadding: 0,
		tickCount: 10,
		tickUnit: '$',
		tickUnitPosition: 'start',
		showZero: true,
		abbreviateTicks: true,
		abbreviateTicksDecimals: 2,
		tickValues: undefined,
		grid: {
			...baseConfig.dependentAxis.grid,
			strokeWidth: 1,
			strokeOpacity: 0,
			strokeDasharray: '5,2',
		},
		ticks: {
			...baseConfig.dependentAxis.ticks,
			strokeWidth: 1,
		},
		axisLabel: {
			...baseConfig.dependentAxis.axisLabel,
			maxWidth: 300,
			padding: 10,
			textAnchor: 'middle',
		},
	},
	independentAxis: {
		...baseConfig.independentAxis,
		scale: 'linear',
		active: true,
		domain: undefined,

		padding: 50,
		showZero: true,
		tickValues: undefined,
		tickCount: 5,
		tickUnitPosition: 'end',
		abbreviateTicks: true,
		abbreviateTicksDecimals: 2,
		ticks: {
			...baseConfig.independentAxis.ticks,
			size: 0,
		},
		axisLabel: {
			...baseConfig.independentAxis.axisLabel,
			padding: 50,
			maxWidth: 300,
			textAnchor: 'middle',
		},
		tickLabels: {
			...baseConfig.independentAxis.tickLabels,
			angle: 0,
			textAnchor: 'middle',
			verticalAnchor: 'middle',
			dx: -50,
			dy: 0,
		},
		grid: {
			...baseConfig.independentAxis.grid,
			strokeWidth: 1,
			strokeOpacity: 1,
			strokeDasharray: '5,2',
		},
		axis: {
			...baseConfig.independentAxis.axis,
			strokeWidth: 0,
		},
	},
	labels: {
		...baseConfig.labels,
		active: true,
		showFirstLastPointsOnly: false,
		color: 'inherit',
		fontWeight: 200,
		fontSize: 12,
		labelPositionDX: 1,
		labelPositionDY: -15,
		toFixedDecimal: 0,
		customLabelFormat: null,
		labelUnit: '$',
		labelUnitPosition: 'start',
	},
	tooltip: {
		...baseConfig.tooltip,
		active: false,
		format: '%1$s: $%2$s',
		offsetX: 110,
		offsetY: 30,
	},
	legend: {
		...baseConfig.legend,
		active: true,
		title: '',
		offsetX: 0,
		offsetY: 0,
		orientation: 'row',
		markerStyle: 'circle',
	},
	metadata: {
		active: true,
		title: 'A really long title that will be truncated and wrapped to fit the available space',
		subtitle: "Sorted based on the value of 'y'",
		note: 'Some Note',
		source: '',
		tag: 'PEW RESEARCH CENTER',
		alt: '',
	},
	voronoi: {
		...baseConfig.voronoi,
		active: true,
	},
	regression: {
		...baseConfig.regression,
		active: true,
	},
};

export default dotPlotConfig;
