import {
  baseConfig,
  BaseConfig as BaseConfigType,
} from '@prc/charting-utilities'

const lineConfig: BaseConfigType = {
  ...baseConfig,
  layout: {
    ...baseConfig.layout,
    type: 'line',
    parentClass: 'wp-chart-builder-wrapper',
    width: 640,
    height: 520,
    padding: { top: 20, bottom: 50, left: 50, right: 50 },
    orientation: 'vertical',
  },
  dataRender: {
    ...baseConfig.dataRender,
    categories: ['Smartphones', 'Tablets', 'PCs'],
    xScale: 'time',
    xFormat: 'MM/YYYY',
    x: 'x',
    y: 'y',
  },
  colors: ['#733D47', '#BC7B86', '#9DC7E1', '#bc7b2b', '#eeece4'],
  line: {
    ...baseConfig.line,
    interpolation: 'curveCatmullRom',
    showPoints: true,
    showArea: true,
    areaFillOpacity: 0.2,
    strokeWidth: 2,
    strokeDasharray: '1, 2',
  },
  nodes: {
    ...baseConfig.nodes,
    pointSize: 5,
    pointFill: 'inherit',
  },
  dependentAxis: {
    ...baseConfig.dependentAxis,
    label: 'Howdy',
    active: true,
    padding: 50,
    domain: [0, 100],
    domainPadding: 0,
    tickCount: 10,
    tickUnit: '$',
    tickUnitPosition: 'start',
    showZero: true,
    abbreviateTicks: true,
    abbreviateTicksDecimals: 2,
    tickValues: undefined,
    grid: {
      ...baseConfig.dependentAxis.grid,
      strokeWidth: 1,
      strokeOpacity: 1,
      strokeDasharray: '5,2',
    },
    ticks: {
      ...baseConfig.dependentAxis.ticks,
      strokeWidth: 1,
    },
  },
  independentAxis: {
    ...baseConfig.independentAxis,
    // label: 'Sup!',
    scale: 'time',
    dateFormat: '%b %Y',
    active: true,
    domain: [0, 100],
    padding: 50,
    showZero: true,
    tickValues: undefined,
    tickCount: 8,
    tickUnitPosition: 'end',
    abbreviateTicks: true,
    abbreviateTicksDecimals: 2,
    ticks: {
      ...baseConfig.independentAxis.ticks,
      size: 8,
    },
    grid: {
      ...baseConfig.independentAxis.grid,
      strokeWidth: 1,
      strokeOpacity: 0,
      strokeDasharray: '5,2',
    },
  },
  labels: {
    ...baseConfig.labels,
    active: true,
    showFirstLastPointsOnly: true,
    color: 'inherit',
    fontWeight: 200,
    fontSize: 12,
    labelUnit: '$',
    labelUnitPosition: 'start',
    labelPositionDX: 10,
    labelPositionDY: -8,
    toFixedDecimal: 0,
  },
  tooltip: {
    ...baseConfig.tooltip,
    active: true,
    headerActive: true,
    format: '%1$s: %2$s%%',
    offsetX: 60,
    offsetY: 20,
    dateFormat: '%Y',
  },
  legend: {
    ...baseConfig.legend,
    active: true,
    title: '',
    offsetX: 0,
    offsetY: 0,
    orientation: 'row',
    markerStyle: 'line',
  },
  voronoi: {
    ...baseConfig.voronoi,
    active: false,
  },
  metadata: {
    ...baseConfig.metadata,
    active: true,
    title: 'Tech adoption over time',
    subtitle: 'Cost of tech adoption',
    note: '',
    source: '',
    tag: 'PEW RESEARCH CENTER',
  },
}

export default lineConfig
